pipeline {
    agent any
    
    triggers {
        pollSCM('H/2 * * * *') // Poll every 5 minutes
    }

    

    environment {
        PORT = '5000'
    }  

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/atomty1/jkn.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        // stage('Start it') {
        //     steps {
        //         sh 'npm start'
        //     }
        // }
    }

    post {
        always {
            echo 'Pipeline Completed'
        }
        success {
            echo 'Pipeline Succeeded'
        }
        failure {
            echo 'Pipeline Failed'
        }
    }
}
